services:
  app:
    build: .
    container_name: step
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm start

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

